### ISSUE TITLE
Aerospike::Exceptions::Connection: Errors

### ISSUE THREAD

**Issue by deenbandhu-agarwal** [aerospike/aerospike-client-ruby#67]
Hi 
I am getting random Aerospike::Exceptions::Connection: end of file reached error at /lib/aerospike/socket/base.rb:  39 . These errors started after upgrading to aerospike 2.7.0 can you tell me what can be the cause of this ?

**Comment by jhecking** [comment]
Do you have a full stack trace? During what database commands does this error occur? And from what version did you upgrade to v2.7?

**Comment by jhecking** [comment]
The EOF error occurs after the client has sent the GET request to the server and is waiting to read the response from the socket. It's not clear to me what might be causing this; so far I was not able to reproduce the issue.

Do you see the error only in GET requests or in other database operations as well? And how frequently does it occur? Do you see any errors or warnings in the Aerospike server logs that correspond with these client-side errors?

**Comment by deenbandhu-agarwal** [comment]
It is occurring in set also. It is getting reproduced on production only and not all the calls are failing. But we are getting somewhere around .2 - .5 % error rate because of this in production. I didn't check aerospike logs till now. I will check and let you know.

**Comment by deenbandhu-agarwal** [comment]
Logs are fine i checked

**Comment by jhecking** [comment]
There have been some changes to the socket handling in v2.6 of the client, in order to add support for TLS encryption. I have reviewed the changes in that version again, and they still look good to me. But to narrow down, whether this is indeed a recently introduced bug, would it be possible for you to temp. downgrade to v2.5(.1) and see if you hit the issue in that version as well?

What would also be helpful is to get a tcp dump of the client/server connections when this issue occurs. But given the low error rates I'm not sure how feasible that is. What's the avg. throughput on your client machines? And do you log the record key when this error occurs? That would help find the affected tcp connection.

Also, what server version are you running and what Ruby version do you use?

**Comment by wallin** [comment]
Just a note. As far as I can tell, errors like these would have been silently swallowed before the tcp code was rewritten to support TLS. So this might have been a latent issue that was not just surfaced before

**Comment by jhecking** [comment]
@wallin, what makes you think the pre-2.6 code would have silently swallowed this kind of error? I believe the old `Connection#read` method would have raised an error on EOF as well:

```ruby
    def read(buffer, length)
      total = 0
      while total < length
        begin
          bytes = @socket.recv_nonblock(length - total)
          if bytes.bytesize > 0
            buffer.write_binary(bytes, total)
          else
            # connection is dead; return an error
            raise Aerospike::Exceptions::Aerospike.new(Aerospike::ResultCode::SERVER_NOT_AVAILABLE, "Connection to the server node is dead.")
          end
          total += bytes.bytesize
        rescue IO::WaitReadable,  Errno::EAGAIN
          IO.select([@socket], nil)
          retry
        rescue => e
          raise Aerospike::Exceptions::Connection.new("#{e}")
        end
      end
    end
```

I think `@socket.recv_nonblock` would return an empty string on EOF, which would raise the `SERVER_NOT_AVAILABLE` exception.

Or am I missing something?

**Comment by deenbandhu-agarwal** [comment]
@jhecking 
The issue is not there in 2.5.1
I did a experiment i continuously called get for a single key and i saw the error coming only few times . So this is not related to some particular key. The issue is not reproduced in v2.5.1 

I am using ruby 2.3
aerospike server version 3.9.1

It is difficult to get the tcp dump because it is very uncertain when the issue come.

**Comment by deenbandhu-agarwal** [comment]
One more observation after i analysed the logs carefully that when i hit a single key continuously the error is coming at a fixed interval of 15 minutes. This might be helpful in debugging the issue

**Comment by khaf** [comment]
Isn’t this supposed to be taken care of by automatic retries?

**Comment by jhecking** [comment]
> Isn’t this supposed to be taken care of by automatic retries?

The Ruby client does not retry the command if the error happens in `parse_result`. Not sure if this differs from how other clients handle retries?

**Comment by khaf** [comment]
That depends on the type of command if it is idempotent to retry, but then why does the connection go bad on that point anyway?

**Comment by jhecking** [comment]
No, it does not depend on whether the command is idempotent. If you look at [`Command#execute`](https://github.com/aerospike/aerospike-client-ruby/blob/b0154073d884abcb48772c6aeb88c179435c867a/lib/aerospike/command/command.rb#L339), it only retries the command if the error happened while writing the command, not if it happened while parsing the result.

While testing, I noticed that if I first write to and then try to read from a TCP socket that has been disconnected by the server, then the write will succeed but the read will raise an EOF error. That matches the behaviour, that deenbandhu is observing. I don't have a good explanation why the connection might have been disconnected in the first place. If it was idle, the server would terminate it after 60 seconds. But that's unlikely to be the case under load, since the client uses all the connections in a round-robin fashion.

**Comment by khaf** [comment]
I meant on the other clients we check if they are one shot or not.

We should do the same in this case too, after we find out what the underlying reason for the connection drop is. 

Maybe it’s deadline related?

**Comment by deenbandhu-agarwal** [comment]
@jhecking  yes i will be able to test it

**Comment by jhecking** [comment]
@deenbandhu-agarwal, I have implemented an experimental connection check feature in the [`check-conn-alive`](https://github.com/aerospike/aerospike-client-ruby/tree/check-conn-alive) branch. It performs a check on all connections retrieved from the connection pool to see if they are alive, and discards connections that are not. The `alive?` check is based on the [`Net::TCPClient`](https://github.com/rocketjob/net_tcp_client) package. The check is only effective if the server closed the connection or if a previous connection failure occurred.

Note that I'm seeing a quite significant performance impact: Throughput in the client benchmark suite is reduce by > 10% if the check is enabled. I'm a bit surprised by this because the check itself should be very efficient.

But before I spent too much time trying to optimize the code (if possible), I would like to find out whether it even helps with your problem in the first place. So can you please give this a spin and let me know if it works?

**Comment by deenbandhu-agarwal** [comment]
@jhecking  I have checked the build on my production servers. There are no connection errors in this build. Please make the required changes for the optimisation. Thanks a lot for helping me out to resolve this issue.

**Comment by deenbandhu-agarwal** [comment]
@jhecking any updates on this ?

**Comment by jhecking** [comment]
Sorry, not yet. I don't have a lot of time to work on the Ruby client at the moment, since I'm busy with another project.

**Comment by deenbandhu-agarwal** [comment]
@jhecking had you planned to work on this or it is still not in plan ?

**Comment by jhecking** [comment]
As I already stated, I haven't had a lot of time to work on this.

I have done a bit more research to find out if there is a way to detect the bad connection on the socket write, but seems there isn't. E.g. ref. https://stackoverflow.com/questions/2530652/ruby-tcpsocket-doesnt-notice-it-when-server-is-killed.

I also did some benchmarking, esp. comparing v2.5.1, v2.6.0 and my dev branch. I noticed that v2.6.0 already is slower compared to v2.5.1, but I haven't been able to pinpoint exactly what is causing this. However, my dev branch is slower yet, and I am continuing to investigate, why.

**Comment by deenbandhu-agarwal** [comment]
@jhecking 
Hi, its been a long do you have any update we are not able to upgrade our ruby client because of this issue. May i help in any sense ?

**Comment by deenbandhu-agarwal** [comment]
@jhecking 
Can you tell me how to run the benchmarking probably I can look into the issue?

**Comment by jhecking** [comment]
Hi @deenbandhu-agarwal,

You can find the benchmark suite for the client here:

https://github.com/aerospike/aerospike-client-ruby/tree/master/tools/benchmark

There are instructions for how to run the benchmark in it's readme.

**Comment by pandurang90** [comment]
Even I am facing the same issue. Any progress on this?

**Comment by islue** [comment]
```
If it was idle, the server would terminate it after 60 seconds.
```
Is the behavior tunable? I can't find the document.

**Comment by jhecking** [comment]
> > If it was idle, the server would terminate it after 60 seconds.
> 
> Is the behavior tunable? I can't find the document.

Yes, this can be configured via the [`proto-fd-idle-ms`](https://www.aerospike.com/docs/reference/configuration/index.html#proto-fd-idle-ms) config setting.

**Comment by pandurang90** [comment]
@jhecking your changes in branch `check-conn-alive` looks good to me as per my requirements regarding performance. Could you also add tests for that?

**Comment by jhecking** [comment]
@deenbandhu-agarwal, v2.8.0 of the client is now available on [rubygems.org](https://rubygems.org/gems/aerospike). Please give it a try. And sorry it took so long to resolve this issue.
